"use client";

import { useState } from "react";
import type { PublicPayPalStatus } from "@/lib/paypal/config";
import type { PreviewPayload } from "@/lib/paypal/token";
import PayPalButton from "../components/PayPalButton";

const CADENCE = { MONTH: "/month", YEAR: "/year", ONE_TIME: " one-time" } as const;

async function postJson(url: string, body: unknown) {
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data?.error ?? `Request failed (${res.status})`);
  return data;
}

export default function PreviewPricing({
  payload,
  token,
  status,
}: {
  payload: PreviewPayload;
  token: string;
  status: PublicPayPalStatus;
}) {
  const [result, setResult] = useState<Record<string, { tone: "ok" | "error"; text: string }>>({});
  const disabledReason = !status.configured
    ? "PayPal sandbox not configured"
    : payload.simulated
      ? "Dry run: simulated plan"
      : null;
  const featured = payload.plans.length >= 3 ? 1 : payload.plans.length - 1;

  return (
    <main className="min-h-screen bg-white px-5 py-8 text-neutral-900">
      <div className="mx-auto max-w-4xl">
        <div className="text-center">
          <span className="inline-flex items-center gap-1.5 rounded-full bg-neutral-100 px-3 py-1 text-[11px] font-medium uppercase tracking-wider text-neutral-600">
            <span className="h-1.5 w-1.5 rounded-full bg-[#0070e0]" />
            Sandbox preview · {payload.site}
          </span>
          <h1 className="mt-4 text-3xl font-bold tracking-tight">{payload.productName} pricing</h1>
          <p className="mt-2 text-sm text-neutral-500">Pick a plan and pay with PayPal. Cancel anytime.</p>
        </div>

        <div className={`mt-8 grid gap-4 ${payload.plans.length >= 3 ? "md:grid-cols-3" : "md:grid-cols-2"}`}>
          {payload.plans.map((p, i) => (
            <div
              key={p.tierId}
              className={`flex flex-col rounded-2xl border p-5 ${
                i === featured ? "border-[#0070e0] shadow-lg shadow-[#0070e0]/10" : "border-neutral-200"
              }`}
            >
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold">{p.name}</h2>
                {i === featured && (
                  <span className="rounded-full bg-[#0070e0]/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-[#0070e0]">
                    Popular
                  </span>
                )}
              </div>
              <div className="mt-3">
                <span className="text-4xl font-bold">${Number(p.amount)}</span>
                <span className="text-sm text-neutral-500">{CADENCE[p.interval]}</span>
              </div>
              {p.description && <p className="mt-2 flex-1 text-sm text-neutral-600">{p.description}</p>}
              <div className="mt-5">
                <PayPalButton
                  sdkUrl={status.sdkUrl}
                  clientId={status.clientId}
                  mode={p.interval === "ONE_TIME" ? "order" : "subscription"}
                  disabledReason={disabledReason}
                  create={async () => (await postJson("/api/preview/checkout", { token, tierId: p.tierId })).id}
                  onApproved={async (id) => {
                    const data =
                      p.interval === "ONE_TIME"
                        ? await postJson("/api/preview/capture", { orderId: id })
                        : await postJson("/api/preview/verify", { subscriptionId: id });
                    setResult((r) => ({
                      ...r,
                      [p.tierId]: { tone: "ok", text: `${data.status}: ${data.captureId ?? id}` },
                    }));
                  }}
                  onError={(text) => setResult((r) => ({ ...r, [p.tierId]: { tone: "error", text } }))}
                />
                {result[p.tierId] && (
                  <p
                    role="status"
                    className={`mt-2 text-xs ${result[p.tierId].tone === "ok" ? "text-green-700" : "text-red-600"}`}
                  >
                    {result[p.tierId].text}
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>

        <p className="mt-6 text-center text-xs text-neutral-400">
          Secure checkout by PayPal · Generated by Shipgrade&apos;s checkout agent
        </p>
      </div>
    </main>
  );
}
